name: unity-buy-sdk

up:
  - ruby: 2.6.0
  - bundler

commands:
  generate:
    syntax:
      argument: type
    desc:   'generate classes from erb class templates'
    run:    scripts/generate.sh
  package:
    syntax:
      argument: type
    desc:   'Publish a new unitypackage for the sdk'
    run:    scripts/publish.sh
  test:
    run: scripts/test_unity.sh
