name: Build .unitypackage

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macOS-latest
    env:
      OUTPUT_PATH: ./Build

    steps:
    - uses: actions/checkout@master

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Use Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app

    - name: Build iOS static libraries
      run: ./PluginDependencies/iOSPlugin/Scripts/build

    - name: Upload library artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ios-plugin-libraries
        path: |
          ./Build/Build/Products/Release-iphoneos/*.a
          ./Build/Build/Products/Release-iphonesimulator/*.a

  package_unity:
    runs-on: ubuntu-latest
    needs: build_ios
    env:
      UNITY_PACKAGE: shopify-buy.unitypackage

    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@v2
      with:
        name: ios-plugin-libraries
        path: ./Assets/Shopify/Plugins/iOS/Shopify

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Generate GraphQL Objects
      run: |
        ./scripts/generate.sh github

    - name: Move over READMEs into doc generation
      run: |
        cat ./scripts/docs/temp_landing.md > ./scripts/docs/landing.md
        cat ./EXAMPLES.md >> ./scripts/docs/landing.md

    - uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: './Doxyfile'

    - name: Copy Examples to Shopify/examples.txt
      run: cp ./EXAMPLES.md ./Assets/Shopify/examples.txt

    - name: Publish .unitypackage
      uses: MirrorNG/unity-runner@3.1.0
      with:
        args: |
          -username ${{ secrets.UNITY_EMAIL }}
          -password ${{ secrets.UNITY_PASSWORD }}
          -serial ${{ secrets.UNITY_SERIAL }}
          -gvh_disable
          -batchmode
          -nographics
          -silent-crashes
          -importPackage ./ThirdParty/external-dependency-manager-1.2.164.unitypackage
          -projectPath ./
          -executeMethod Publishing.PublishFromCommandLine
          -quit $UNITY_PACKAGE

    - name: Upload .unitypackage
      uses: actions/upload-artifact@v2
      with:
        name: unity-package
        path: ./*.unitypackage











