name: Test Unity

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    steps:
    - uses: actions/checkout@master

    - name: Cache Unity Library
      uses: actions/cache@v2
      with:
        path: Library
        key: Library

    - name: Unity - Test runner
      uses: game-ci/unity-test-runner@v2.0-alpha-2
      env:
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL}}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD}}
      with:
        projectPath: .
        unityVersion: 2019.4.18f1

    - uses: actions/upload-artifact@v1
      with:
        name: Test results
        path: artifacts